**TO DO**: remove _unused_ functions from `/utils/snt_dhis2_incidence.r` ... !

## 1. Setup

In [110]:
PIPELINE_NAME <- "snt_dhis2_incidence"

### 1.0. Fallback parameters

### ⚠️⚠️⚠️ TEMP FOR DEV !!! ⚠️⚠️⚠️

In [ ]:
USE_CARESEEKING_FROM_FILE <- TRUE # Now use this as temporary switch to simulate presence of user provided file
# Simuate pipeline paramter for careseeking file path
# To be deleted after pipeline.py is ready to handle this!

if (exists("CARESEEKING_FILE_PATH")) rm(CARESEEKING_FILE_PATH)

if (USE_CARESEEKING_FROM_FILE) {
  # uploads/NER_careseeking_template_TEST.csv
  CARESEEKING_FILE_PATH <- "~/workspace/uploads/NER_careseeking_template_TEST.csv"
#   print(CARESEEKING_FILE_PATH)
}

if (exists("CARESEEKING_FILE_PATH")) {
    print(paste("careseeking file path provided:", CARESEEKING_FILE_PATH))
} else {
    print("No careseeking file path provided.")
}

rm(USE_CARESEEKING_FROM_FILE) # Clean up temporary variable

[1] "careseeking file path provided: ~/workspace/uploads/NER_careseeking_template_TEST.csv"

In [ ]:
# ----- ⚡ Defined in pipeline.py code ---------------

if (!exists("N1_METHOD")) N1_METHOD <- "SUSP-TEST" # ⚡ For N1 calculations: use `SUSP-TEST` or `PRES`
if (!exists("ROUTINE_DATA_CHOICE")) ROUTINE_DATA_CHOICE <- "raw" # "raw" "raw_without_outliers" "imputed"
# if (!exists("USE_CSB_DATA")) USE_CSB_DATA <- FALSE # OLD 
if (!exists("USE_ADJUSTED_POPULATION")) USE_ADJUSTED_POPULATION <- FALSE # ⚡ USE_ADJUSTED_POPULATION bool 

# 👥 Population Disaggregation 
# Only for countries in which disaggregated data is available. Pipeline fails if you select something you don't have.
if (!exists("DISAGGREGATION_SELECTION")) DISAGGREGATION_SELECTION <- NULL # Options: "PREGNANT_WOMAN", "UNDER_5", ... 
# Disaggregation options set in pipeline.py parameters, based on 
# https://bluesquare.atlassian.net/browse/SNT25-363?focusedCommentId=85587

### 1.1. Run setup

#### `source()`

In [113]:
install.packages("here")
# source("~/workspace/pipelines/snt_dhis2_incidence/code/snt_dhis2_incidence.r")
source(file.path(here::here(), "pipelines", PIPELINE_NAME, "utils", paste0(PIPELINE_NAME, ".r")))

Updating HTML index of packages in '.Library'

Making 'packages.html' ...
 done

This step sets up the environment for the DHIS2 incidence pipeline, including paths, config, and utility functions.
It basically handles all the boring stuff so that you can focus on the code that matters :)

In [114]:
load_utils()
setup_paths()
create_intermediate_data_dir()

Utils loaded from: /home/hexa/workspace/code/snt_utils.r

Palettes loaded from: /home/hexa/workspace/code/snt_palettes.r

Paths set up:

SNT_ROOT_PATH/home/hexa/workspace

CODE_PATH: /home/hexa/workspace/code

PIPELINE_PATH: /home/hexa/workspace/pipelines/snt_dhis2_incidence

CONFIG_PATH: /home/hexa/workspace/configuration

DATA_PATH: /home/hexa/workspace/data/dhis2/incidence

INTERMEDIATE_DATA_PATH: /home/hexa/workspace/data/dhis2/incidence/intermediate_results

In [115]:
# List required pcks
required_packages <- c("arrow", "tidyverse", "stringi", "jsonlite", "httr", "reticulate", "glue")
install_and_load(required_packages)

              arrow           tidyverse             stringi            jsonlite
     "arrow 18.1.0"   "tidyverse 2.0.0"     "stringi 1.8.7"    "jsonlite 1.8.9"
               httr          reticulate                glue
       "httr 1.4.8" "reticulate 1.45.0"        "glue 1.7.0"

In [116]:
set_env_openhexa()

Python config:

python:         /opt/conda/bin/python
libpython:      /opt/conda/lib/libpython3.13.so
pythonhome:     /opt/conda:/opt/conda
version:        3.13.11 | packaged by conda-forge | (main, Dec  6 2025, 11:24:03) [GCC 14.3.0]
numpy:          /opt/conda/lib/python3.13/site-packages/numpy
numpy_version:  2.3.5

NOTE: Python version was forced by RETICULATE_PYTHON

Openhexa SDK imported successfully.

### 1.2. Load and check `config` file

**Checks for SNT mandatory configuration fields**

In [117]:
import_config_json()
config_generic()
config_incidence()
set_fixed_cols()

SNT configuration loaded from: /home/hexa/workspace/configuration/SNT_config.json
Configuration values set: COUNTRY_CODE=NER, ADMIN_1=LEVEL_2_NAME, ADMIN_2=LEVEL_3_NAME
DHIS2 indicators set: SUSP, SUSP_UNDER_5, SUSP_ABOVE_5, SUSP_PREGNANT_WOMAN, TEST, TEST_UNDER_5, TEST_ABOVE_5, TEST_PREGNANT_WOMAN, CONF, CONF_UNDER_5, CONF_ABOVE_5, CONF_PREGNANT_WOMAN, PRES, PRES_UNDER_5, PRES_ABOVE_5, PRES_PREGNANT_WOMAN, MALTREAT, MALTREAT_UNDER_5, MALTREAT_ABOVE_5, MALTREAT_PREGNANT_WOMAN, MALSIMP, MALSIMP_UNDER_5, MALSIMP_ABOVE_5, MALSIMP_PREGNANT_WOMAN, MALSEV, MALSEV_UNDER_5, MALSEV_ABOVE_5, MALSEV_PREGNANT_WOMAN, MALDTH, MALDTH_UNDER_5, MALDTH_ABOVE_5, MALDTH_PREGNANT_WOMAN, MALADM, MALADM_UNDER_5, MALADM_ABOVE_5, MALADM_PREGNANT_WOMAN, ALLADM, ALLDTH, ALLOUT, TPI1, TPI3, CPN, MILDA_CPN, MILDA_VAR, VAR1, UTILISATION
Fixed routine data ('dhis2_routine') columns set: OU_ID, PERIOD, YEAR, MONTH, ADM1_ID, ADM2_ID

## 2. Load Data

### 2.1. **Routine** data (DHIS2) (parametrized choice)

In [118]:
select_routine_dataset_and_filename()

Selected routine dataset: snt-dhis2-formatted, filename: NER_routine.parquet

In [119]:
load_dhis2_routine_data()

[1] "File downloaded successfully from dataset version: SNT_NER_20260317_1532"
[1] "DHIS2 routine data : NER_routine.parquet loaded. Dims: 200179, 55"

  PERIOD YEAR MONTH OU_ID       OU_NAME        ADM1_NAME ADM1_ID
1 202201 2022 1     A0L1KvXYiSD CS Guido       ZINDER    epuzC0EVaWn
2 202201 2022 1     A0MFn6k91gn CS Agabargabar AGADEZ    soev4fKEhm0
3 202201 2022 1     A17GOu2SJ4V CSI Mazamni    ZINDER    epuzC0EVaWn
  ADM2_NAME          ADM2_ID     SUSP ⋯ ALLADM ALLDTH ALLOUT TPI1 TPI3 CPN
1 DS GOURE           CwgbNoqVy6u  19  ⋯ NA     NA      33     NA  NA    NA
2 DS INGALL          ILzVs1aSIB2  NA  ⋯ NA     NA      95     NA  NA    NA
3 DS DAMGARAM TAKAYA v6glfHYkE77 273  ⋯ NA     NA     446    154  80   346
  MILDA_CPN MILDA_VAR VAR1 UTILISATION
1  NA       NA        NA    33
2  NA       NA        NA    95
3 154       79        79   446

#### Checks

... on routine data columns

In [120]:
# `fixed_cols`: Fixed columns that should be always present regardless of the config.
check_fixed_cols_in_routine()

# `DHIS2_INDICATORS`: Indicators, as defined in the config.json file, 
#   are expected to be present if the extraction pipeline and this pipeline are run on the same config settings.
check_dhis2_indicators_cols_in_routine()

[1] "All expected 'fixed' columns present."
[1] "All DHIS2 indicators present in 'dhis2_routine'."

... on `N1_METHOD` selected: <br>
_**if**_ `N1_METHOD == PRES` then `PRES` must exist in config.json file _and_ in routine data <br>
_**else**_ N1 will use `SUSP-TEST` instead

In [121]:
check_PRES_col()

[1] "N1_METHOD is not set to 'PRES'. No need to check for `PRES` column."

### 2.2. **Population** data at level `ADM2` x `YEAR`

In [122]:
load_population_data()

[1] "File downloaded successfully from dataset version: SNT_NER_20260317_1532"
DHIS2 population data loaded from snt-dhis2-formatted.

  YEAR ADM1_NAME ADM1_ID     ADM2_NAME       ADM2_ID     POPULATION POP_UNDER_5
1 2022 AGADEZ    soev4fKEhm0 DS ADERBISSINAT peHhT5RvVls   48458     9463
2 2022 AGADEZ    soev4fKEhm0 DS AGADEZ       vT8InUQZKJb 1667033    31244
3 2022 AGADEZ    soev4fKEhm0 DS ARLIT        UcnWjaPG0mh  144092    28148
  POP_PREGNANT_WOMAN
1  2541
2 10507
3  7555

### 👥 Population Disaggregation logic

In [123]:
# 👥 Resolve col names for disaggregated values
prepare_disaggregated_indicators(dhis2_routine, DISAGGREGATION_SELECTION, N1_METHOD)

[1] "Population Disaggregation: No disaggregation applied based on the current configuration."

In [124]:
# 👥 Replace col `POPULATION` with selected disaggregated population col (if found)
# (aka "mapping")
select_population_column(dhis2_population_adm2, DISAGGREGATED_INDICATORS_FOUND, DISAGGREGATION_SELECTION)

[1] "Population Disaggregation: No disaggregation applied based on the current configuration."

#### 2.2.1 **Population** data columns selection.

In [125]:
dhis2_population_adm2 <- dhis2_population_adm2 |> 
select(YEAR, ADM1_NAME, ADM1_ID, ADM2_NAME, ADM2_ID, POPULATION) 

dim(dhis2_population_adm2)
head(dhis2_population_adm2, 3)

[1] 288   6

  YEAR ADM1_NAME ADM1_ID     ADM2_NAME       ADM2_ID     POPULATION
1 2022 AGADEZ    soev4fKEhm0 DS ADERBISSINAT peHhT5RvVls   48458
2 2022 AGADEZ    soev4fKEhm0 DS AGADEZ       vT8InUQZKJb 1667033
3 2022 AGADEZ    soev4fKEhm0 DS ARLIT        UcnWjaPG0mh  144092

### 2.3. (optional) **Care Seeking Behaviour** (CSB) 
Aka "taux recherche soins"

In [ ]:
exists("CARESEEKING_FILE_PATH")

[1] TRUE

In [ ]:
# The logic here is to check if the careseeking file exists. 
# If found, we will load it (and use it for N3 calculations later);
# if not found, we will issue a warning & then look for DHS data.
#  If DHS data is found, we will use it for careseeking adjustment and N3 calculations.
#  If DHS data is not found, we will issue a warning and skip N3 calculations.
IMPORTED_CARESEEKING_FROM_FILE <- FALSE
IMPORTED_CARESEEKING_FROM_DHS <- FALSE

if (exists("CARESEEKING_FILE_PATH") && file.exists(CARESEEKING_FILE_PATH)) { # ⚡ TO BE Injected by pipeline.py as parameter ⚡
        careseeking_data <- read_csv(CARESEEKING_FILE_PATH, show_col_types = FALSE)
        # Ensure CARESEEKING_PCT is numeric (since it's user input it might have been read as character)
        # This will break if the column is not found or has non-numeric values, which is why we will check for expected columns next.
        careseeking_data$CARESEEKING_PCT <- as.numeric(careseeking_data$CARESEEKING_PCT) 
        # Add check for expected columns in careseeking_data: must have "ADM1_ID" and "CARESEEKING_PCT" columns
        if (!all(c("ADM1_ID", "CARESEEKING_PCT") %in% colnames(careseeking_data))) {
            log_msg("⚠️ Careseeking data does not have the expected columns. Setting careseeking_data to NULL.", "warning")
            careseeking_data <- NULL
        } else {
        log_msg(paste("✅ Careseeking data loaded successfully from ", CARESEEKING_FILE_PATH, ". This will be used for N3 calculations."))
        IMPORTED_CARESEEKING_FROM_FILE <- TRUE
        }        
    } else {
        log_msg(paste("Careseeking file not found. Looking at DHS data instead."), "warning")
        load_dhs_careseeking_data()
        if (!is.null(dhs_careseeking_data)) {
            log_msg("✅ Careseeking data loaded successfully from DHS data. This will be used for N3 calculations.")
            careseeking_data <- dhs_careseeking_data
            IMPORTED_CARESEEKING_FROM_DHS <- TRUE
        } else {
            log_msg("⚠️ DHS data not found at ... Skipping N3 calculations.", "warning")
            # Set careseeking_data ad null for next step ... or not needed?
            careseeking_data <- NULL
        }
    }

[1] "✅ Careseeking data loaded successfully from  ~/workspace/uploads/NER_careseeking_template_TEST.csv . This will be used for N3 calculations."

In [129]:
head(careseeking_data, 3)

  ADM1_NAME ADM1_ID     CARESEEKING_PCT
1 AGADEZ    soev4fKEhm0 0.48
2 DIFFA     e5QYN69Wyri 0.61
3 DOSSO     EWBHLyo4PQJ 0.67

### 2.4. Load Reporting Rate 

Import Reporting Rate file based on what is available in the latest OH Dataset version (which depends on last run reporting rate pipepline).

📅 **Important**: reporting rate must be **monthly**!

In [130]:
load_reporting_rate_data()

[1] "File downloaded successfully from dataset version: SNT_NER_20260226_2041"
Reporting Rate data: `NER_reporting_rate_dataelement.parquet` loaded from dataset: `snt-dhis2-reporting-rate`. Dataframe dimensions: 3456, 4
Final Reporting Rate (dataelement) data frame dimensions: 3456, 4

  YEAR MONTH ADM2_ID     REPORTING_RATE
1 2022 1     DwXVZS6eH3C 0.9021739
2 2022 2     DwXVZS6eH3C 0.8478261
3 2022 3     DwXVZS6eH3C 0.8043478

#### 🔍 Checkon data completeness for `REPORTING_RATE` data
Normally we should have "complete" data (no missing or `NA` values). However, when using certain datasets (from pipeline: "Reporting Rate (Dataset)") we might have incomplete coverage and hence `NA`s ... <br>
These are "problematic" because **N2** (Incidence adj 2) will also have `NA` values.

In [131]:
check_reporting_rate_data()

[1] "✅ Reporting Rate data contains no missing values (NA) in 'REPORTING_RATE' column."

-------------------------------

## 3. Calculate Incidence
First calculate monthly cases, then yearly incidence.

### 3.1 **Monthly cases**


These methods follow the standard WHO approach for estimating malaria incidence from routine health information systems (WHO, 2023).
As shown in the code, we begin by calculating **monthly malaria case metrics** (confirmed, tested, presumed) at the **ADM2** level and join them with the **monthly reporting rate**. 

This allows us to compute the **test positivity rate** (TPR, where `TPR` = `CONF` / `TEST`) and adjust for incomplete testing using the formula: 
> **N1** = `CONF` + (`PRES` × `CONF` / `TEST`)

Which is equivalent to:
> **N1** = `CONF` + (`PRES` × **TPR**)

where:
- **N1** = cases adjusted for testing gaps 
- `CONF` = **confirmed** cases
- `PRES` = **presumed** cases (either `SUSP` - `TEST` or directly available as `PRES`) 👈 this is a parameter (`N1_METHOD`)
- `TEST` = **tested** cases 
- **TPR** = Test Positivity Rate (`CONF` / `TEST`)
  
This produces `N1`, the number of cases adjusted for testing gaps, calculated at the monthly level in line with WHO recommendations to capture intra-annual variation.

Next, we adjust for incomplete reporting using: 
> **N2** = **N1** / `REPORTING_RATE`

where `REPORTING_RATE` is at the monthly levele, and is the ratio of received reports (submission to DHIS2) divided by the expected reports.

Finally, _if_ **careseeking** data is **available**, N3 is calculated as follows:
> **N3** = N2 + (N2 * PROP_PRIV / PROP_PUBL) + (N2 * NO_TREAT / PROP_PUBL)

where:
- PRIVATE_CARE = proportion of kids treated in the **private** sector
- PUBLIC_CARE = proportion of kids treated in the **public** sector
- NO_CARE = proportion of kids which **did not receive any treatment**

Note that this assumes the same TPR across all sectors (private and public).



**Important note**<br>
In case reporting rate equals zero (none of the health facilities reported in a given month), N2 is set to `NA`. Note that the annual N2 will be underestimated, which is preferable compared to having `Inf` values.

-------------

This calculation expects (input):
* **routine_data**: DHIS2 routine data, formatted and aggregated at ADM2 and MONTH level. Tibble (df) _must_ contain the following cols: `YEAR`, `MONTH`, `ADM2`, `CONF`, `TEST`, `SUSP`, `PRES`.  
* **reporting_rate_data**: reporting rate calculated at ADM2 and MONTH level and expressed as proprtion **(0-1)**. Tibble (df) _must_ contain the following cols: `ADM2`, `YEAR`, `MONTH`, `reporting_rate`

The calculation produces (output):
* data frame with the following cols: `ADM2`, `YEAR`, `MONTH`, "value_" * (`CONF`, `TEST`, `SUSP`, `PRES`), `TPR`, `N1`, `N2`

-----------------

In [132]:
enforce_numeric_cols()

[1] "Created 'routine_data' dataframe. Ensured correct data types for DHIS2 routine data numerical columns: YEAR, MONTH, CONF, TEST, SUSP, PRES."
[1] "Created 'reporting_rate_data' dataframe. Ensured correct data types for Reporting Rate data numerical columns: YEAR, MONTH, REPORTING_RATE."

#### 3.1.0. Aggregate at `ADM2` x `MONTH` & calculate **TPR**

In [ ]:
# Group & compute TPR
monthly_cases <- routine_data |>
    group_by(ADM1_ID, ADM2_ID, YEAR, MONTH) |> # ADM1 is needed to join careseeking data
    summarise(
      CONF = sum(CONF, na.rm = TRUE),
      TEST = sum(TEST, na.rm = TRUE),
      SUSP = sum(SUSP, na.rm = TRUE),
      across(any_of("PRES"), ~sum(., na.rm = TRUE), .names = "PRES"), # to handle missing 'PRES' column gracefully
      .groups = "drop") |>
    # Cleaning TEST data for "SUSP-TEST" method
    mutate(TEST = ifelse(N1_METHOD == "SUSP-TEST" & !is.na(SUSP) & (TEST > SUSP), SUSP, TEST)) |>
    left_join(reporting_rate_data,
              by = c("ADM2_ID", "YEAR", "MONTH")) |>   
    # Calculate TPR based on CONF and TEST
    # Note: if TEST is 0 or NA, set TPR = 1 (to avoid division by zero which produces Inf)
    mutate( 
      TPR = ifelse(!is.na(CONF) & !is.na(TEST) & (TEST != 0), CONF / TEST, 1)
    )

#### 3.1.1. Calculate **N1**

In [134]:
# Calculate N1 based on `N1_METHOD` & availability of `PRES` 

if (N1_METHOD == "SUSP-TEST") {
    monthly_cases <- monthly_cases %>%
      mutate(N1 = CONF + ((SUSP - TEST) * TPR))
      log_msg("Calculating N1 as `N1 = CONF + ((SUSP - TEST) * TPR)`")
} else if (N1_METHOD == "PRES") {
    # if: column named "PRES" exists in `monthly_cases` and contains at least one non-missing value
    if ("PRES" %in% names(monthly_cases) && !all(is.na(monthly_cases$PRES))) {
      monthly_cases <- monthly_cases %>%
        mutate(N1 = CONF + (PRES * TPR))
        log_msg("ℹ️ Calculating N1 as `N1 = CONF + (PRES * TPR)`")
    } else {
      log_msg("🚨 Warning: 'PRES' not found in routine data or contains all `NA` values! 🚨 Calculating N1 using 'SUSP-TEST' method instead.")
      monthly_cases <- monthly_cases %>%
        mutate(N1 = CONF + ((SUSP - TEST) * TPR))
    }
} else {
    log_msg("Invalid N1_METHOD. Please use 'PRES' or 'SUSP-TEST'.") # not really necessary ... 
}

[1] "Calculating N1 as `N1 = CONF + ((SUSP - TEST) * TPR)`"

#### 3.1.2. Calculate **N2**

In [135]:
# Calculate N2
monthly_cases <- monthly_cases %>%
    mutate(
      N2 = ifelse(REPORTING_RATE == 0, NA_real_, N1 / REPORTING_RATE) # On the fly convert `RR == 0` to NA to avoid N2 == Inf
    )

In [136]:
handle_zeros_in_reporting_rate()

[1] "✅ Note: no ADM2 has `REPORTING_RATE == 0`. All N2 values were preserved."

#### 3.1.4. (optional) Calculate **N3**

In [ ]:
# 🚨 New: define colname depening of which file we're using for careseeking data: user provided vs DHS 
if (IMPORTED_CARESEEKING_FROM_FILE) {
    careseeking_pct_col <- "CARESEEKING_PCT"
} else if (IMPORTED_CARESEEKING_FROM_DHS) {
    careseeking_pct_col <- "PCT_PUBLIC_CARE"
} else {
    careseeking_pct_col <- NULL
}

print(paste("Careseeking percentage column used for N3 calculations:", careseeking_pct_col))

[1] "Careseeking percentage column used for N3 calculations: CARESEEKING_PCT"

In [138]:
# Only calculate N3 if CARESEEKING data is avaiable 
if (!is.null(careseeking_data)) {
    monthly_cases <- monthly_cases |>
    mutate(YEAR = as.numeric(YEAR)) |> # keep as safety
    left_join(careseeking_data, by = c("ADM1_ID")) |>
    mutate(
        # N3 = N2 + (N2 * PCT_PRIVATE_CARE / PCT_PUBLIC_CARE) + (N2 * PCT_NO_CARE / PCT_PUBLIC_CARE) # OLD formula (unnecessarily complicated)
        # N3 = N2 / !!sym(careseeking_pct_col) # Simplified
        N3 = ifelse(!!sym(careseeking_pct_col) == 0, NA_real_, N2 / !!sym(careseeking_pct_col)) # avoid N2 == Inf
    )
} else {
    print("🦘 Careseeking data not available, skipping calculation of N3.")
}

In [139]:
head(monthly_cases, 3)

  ADM1_ID     ADM2_ID     YEAR MONTH CONF TEST  SUSP  PRES REPORTING_RATE
1 BMNYTSyLiKu DwXVZS6eH3C 2022 1     5197 11698 11752 270  0.9021739
2 BMNYTSyLiKu DwXVZS6eH3C 2022 2     4181  9557  9579 245  0.8478261
3 BMNYTSyLiKu DwXVZS6eH3C 2022 3     3459 10535 10685 245  0.8043478
  TPR       N1       N2       ADM1_NAME CARESEEKING_PCT N3
1 0.4442640 5220.990 5787.122 TAHOUA    0.7             8267.317
2 0.4374804 4190.625 4942.788 TAHOUA    0.7             7061.126
3 0.3283341 3508.250 4361.608 TAHOUA    0.7             6230.869

#### 💾 Export `monthly_cases` (for 📓report notebook)
For coherence checks, which need monthly resolution ... !

In [140]:
export_monthly_cases(monthly_cases)

Monthly cases data saved to: /home/hexa/workspace/data/dhis2/incidence/intermediate_results/NER_monthly_cases.parquet

### 🔍 Data **coherence** checks on **monthly cases**
Check for ratios or differences that will cause negative values -> which will causes adjusted incidence to be lower than the values it adjust


Namely, the following relationships among INDICATORs:
* SUSP-TEST
* CONF/TEST
* N1 == CONF ... (when PRES == 0)

#### 1. `PRES == 0`: causes `N1 == CONF` 
(if `N1_METHOD == "PRES"`)

In [141]:
coherence_check_PRES(monthly_cases)

[1] "N1_METHOD is not set to 'PRES'. No need to check for coherence of `PRES` column."

#### 2. `SUSP-TEST`: if negative, then N1 smaller or equal to CONF (ADJ =< CRUDE)
(if `N1_METHOD == "SUSP-TEST"`)

In [142]:
coherence_check_SUSP_TEST(monthly_cases)

[1] "✅ Note: using `SUSP - TEST` for incidence adjustment, no cases where `TEST > SUSP` detected."

#### 3. `CONF/TEST` = `TPR` (to calculate N1: Incidence adjusted for **Testing**)
This **ratio should** always be **≤ 1** because **there should _not_ be more confirmed cases than tested** ...

(but if very small, then N1 could be smaller or equal to CONF (so ADJ INC ≤ CRUDE))

In [143]:
coherence_check_CONF_TEST(monthly_cases)

[1] "✅ Note: no cases where `CONF > TEST` detected."

### 3.2 **Yearly incidence**
After calculating N1 and N2 for each `ADM2`-`MONTH`, we aggregate the data annually to compute the yearly totals (sums) for crude cases (`CONF`), `N1` and `N2`. Finally, we compute:
* Crude incidence: C / POP × 1000
* Incidence adjusted for testing: N1 / POP × 1000
* Incidence adjusted for testing and reporting: N2 / POP × 1000
* Incidence adjusted for testing, reporting and careseeking behaviour (optional): N3 / POP × 1000
* ⚠️⚠️⚠️ **TO DO: add option of CSB from custom source ... (`care_seeking_data_f`)** ⚠️⚠️⚠️

--------------

The calculation expects (input):
* **monthly_cases**: as the output of `calculate_monthly_cases()`, or a tibble/data frame with the following cols: `ADM2`, `YEAR`, `MONTH`, "value_" * (CONF, TEST, SUSP, PRES), `TPR`, `N1`, `N2`  
* **population_data**: df of population data formatted and aligned, aggregated at ADM2 and YEAR level. A tibble/data frame that _must_ contain the following cols: `ADM2`, `YEAR`, `POPULATION`

The calculation produces (output): 
* a data frame with the following cols: ADM2_ID, YEAR, CONF, N1, N2, `INCIDENCE_CRUDE`, `INCIDENCE_ADJ_TESTING`, `INCIDENCE_ADJ_REPORTING`

--------------------

In [144]:
# ---- 1. Enforce column types upfront ----
monthly_cases <- monthly_cases %>% 
    mutate(across(where(is.numeric), as.numeric))  # Convert all numeric columns
  
population_data <- dhis2_population_adm2 %>% # population_data
    mutate(across(c(YEAR, POPULATION), as.numeric))

In [145]:
# ---- 2. Core calculation ----
yearly_incidence <- monthly_cases %>%
    group_by(ADM2_ID, YEAR) %>%
    summarise(
        # 🚨 removed `na.rm = TRUE` on 20250702 - if things break check here! 🚨 
      across(c(CONF, N1, N2), ~sum(.)), #, na.rm = TRUE)), # 🔍 PROBLEM: if NA's in N2 (due to missing RR data), the sum of N2 by YEAR is smaller than the sum of N1 !
      .groups = "drop"
    ) %>%
    left_join(
      population_data,
      by = c("ADM2_ID", "YEAR")
    ) %>%
    mutate(
      INCIDENCE_CRUDE = CONF / POPULATION * 1000,
      INCIDENCE_ADJ_TESTING = N1 / POPULATION * 1000,
      INCIDENCE_ADJ_REPORTING = N2 / POPULATION * 1000
    ) |>
    ungroup()

In [146]:
# careseeking_data
monthly_cases |> head()

  ADM1_ID     ADM2_ID     YEAR MONTH CONF TEST  SUSP  PRES REPORTING_RATE
1 BMNYTSyLiKu DwXVZS6eH3C 2022 1     5197 11698 11752 270  0.9021739
2 BMNYTSyLiKu DwXVZS6eH3C 2022 2     4181  9557  9579 245  0.8478261
3 BMNYTSyLiKu DwXVZS6eH3C 2022 3     3459 10535 10685 245  0.8043478
4 BMNYTSyLiKu DwXVZS6eH3C 2022 4     3471  9546  9546 192  0.7934783
5 BMNYTSyLiKu DwXVZS6eH3C 2022 5     3099  9130  9130 155  0.8043478
6 BMNYTSyLiKu DwXVZS6eH3C 2022 6     2681  8641  8732 123  0.8478261
  TPR       N1       N2       ADM1_NAME CARESEEKING_PCT N3
1 0.4442640 5220.990 5787.122 TAHOUA    0.7             8267.317
2 0.4374804 4190.625 4942.788 TAHOUA    0.7             7061.126
3 0.3283341 3508.250 4361.608 TAHOUA    0.7             6230.869
4 0.3636078 3471.000 4374.411 TAHOUA    0.7             6249.159
5 0.3394304 3099.000 3852.811 TAHOUA    0.7             5504.015
6 0.3102650 2709.234 3195.507 TAHOUA    0.7             4565.010

In [147]:
# ---- 3.1 Optional careseeking data CSV adjustment ---- 
if (!is.null(careseeking_data) && "N3" %in% names(monthly_cases)) {
    n3_data <- monthly_cases %>%
      group_by(ADM2_ID, YEAR) %>%
      summarise(N3 = sum(N3, na.rm = TRUE),
                .groups = "drop") |>
      ungroup()
    
    yearly_incidence <- yearly_incidence %>%
      left_join(n3_data, by = c("ADM2_ID", "YEAR")) %>%
      mutate(
        INCIDENCE_ADJ_CARESEEKING = N3 / POPULATION * 1000
      )
  } else {
    yearly_incidence <- yearly_incidence |>
      mutate(
        INCIDENCE_ADJ_CARESEEKING = NA
            )
  }

In [148]:
head(yearly_incidence, 3)

  ADM2_ID     YEAR CONF  N1       N2       ADM1_NAME ADM1_ID     ADM2_NAME
1 AXYBpkHRL1P 2022 74990 75045.25 82205.49 TILLABERI K02vqWrzyEO DS GOTHEYE
2 AXYBpkHRL1P 2023 64420 64968.03 70852.80 TILLABERI K02vqWrzyEO DS GOTHEYE
3 AXYBpkHRL1P 2024 64699 64699.48 68504.62 TILLABERI K02vqWrzyEO DS GOTHEYE
  POPULATION INCIDENCE_CRUDE INCIDENCE_ADJ_TESTING INCIDENCE_ADJ_REPORTING
1 345615     216.9755        217.1354              237.8528
2 358609     179.6385        181.1668              197.5767
3 372110     173.8706        173.8719              184.0978
  N3       INCIDENCE_ADJ_CARESEEKING
1 182678.9 528.5617
2 157450.7 439.0594
3 152232.5 409.1062

### 🔍 Data **coherence** checks on **yearly incidence**
Here we check if values of Indicidence (already at `YEAR` resolution) make sense in relation to each other.<br>
Namely:
* crude values should be the lowest, and any consecutive **adjustment** should cause the incidence values to **increase** or remain the **same** - but should never be lower!

#### 1. `INCIDENCE_ADJ_TESTING` (adj. level 1) should always be greater than `INCIDENCE_CRUDE` (not adjusted)

In [149]:
coherence_checkes_yearly_incidence(yearly_incidence, incidence_col_1 = "INCIDENCE_CRUDE", incidence_col_2 = "INCIDENCE_ADJ_TESTING")

✅ For all YEAR and ADM2, `INCIDENCE_CRUDE` is smaller than `INCIDENCE_ADJ_TESTING` (as expected).

#### 2. `INCIDENCE_ADJ_REPORTING` (adj. level 2) should always be greater than `INCIDENCE_ADJ_TESTING` (adj. level 1)

In [150]:
coherence_checkes_yearly_incidence(yearly_incidence, incidence_col_1 = "INCIDENCE_ADJ_TESTING", incidence_col_2 = "INCIDENCE_ADJ_REPORTING")

✅ For all YEAR and ADM2, `INCIDENCE_ADJ_TESTING` is smaller than `INCIDENCE_ADJ_REPORTING` (as expected).

## 4. Export to `/data/dhis2_incidence/` folder

### 4.0. Keep only essential cols 
Based on [SNT Pipelines Data glossary](https://docs.google.com/spreadsheets/d/1qvZMsmCWU6cVLgGZTEXsd5xmoecIxb4LAd-g_2qzYdw/edit?usp=sharing)

In [151]:
yearly_incidence <- yearly_incidence |>
select(
    YEAR, 
    starts_with("ADM"),
    starts_with("POPULATION"),
    starts_with("INCIDENCE")
)

In [152]:
yearly_incidence |> head()

  YEAR ADM2_ID     ADM1_NAME ADM1_ID     ADM2_NAME  POPULATION INCIDENCE_CRUDE
1 2022 AXYBpkHRL1P TILLABERI K02vqWrzyEO DS GOTHEYE 345615     216.9755
2 2023 AXYBpkHRL1P TILLABERI K02vqWrzyEO DS GOTHEYE 358609     179.6385
3 2024 AXYBpkHRL1P TILLABERI K02vqWrzyEO DS GOTHEYE 372110     173.8706
4 2025 AXYBpkHRL1P TILLABERI K02vqWrzyEO DS GOTHEYE 395130     207.4229
5 2022 Ba9fjaGqMvm ZINDER    epuzC0EVaWn DS TAKEITA 353885     210.1615
6 2023 Ba9fjaGqMvm ZINDER    epuzC0EVaWn DS TAKEITA 367326     208.0713
  INCIDENCE_ADJ_TESTING INCIDENCE_ADJ_REPORTING INCIDENCE_ADJ_CARESEEKING
1 217.1354              237.8528                528.5617
2 181.1668              197.5767                439.0594
3 173.8719              184.0978                409.1062
4 209.3625              216.9538                482.1196
5 210.1615              212.2108                451.5123
6 212.1178              247.4286                526.4439

#### 👥 Population Disaggregation logic 

Provide a msg to the user to indicate that the results correspond to a specific version of indicators and population (under5, pregnant or totals).

In [153]:
if (DISAGGREGATED_INDICATORS_FOUND) {
    log_msg(glue("ℹ️ The results have been computed using the following Indicators: {paste(target_colnames, collapse=', ')}"))
    log_msg(glue("ℹ️ The results have been computed using the following Population: {POPULATION_SELECTION}"))
}

In [156]:
# Tell the user what data and col were used for careseeking adjustment, if applicable
if (!is.null(careseeking_data) && "N3" %in% names(monthly_cases)) {
    second_part_of_log <- if (IMPORTED_CARESEEKING_FROM_FILE) {
        glue("user-provided file.")
    } else if (IMPORTED_CARESEEKING_FROM_DHS) {
        glue("DHS data {careseeking_file_name}.")
    } 
    log_msg(glue("The results have been computed using careseeking adjustment based on the column '{careseeking_pct_col}' from the {second_part_of_log}"))
} else {
    log_msg("No careseeking adjustment applied since careseeking data was not available.")
}

The results have been computed using careseeking adjustment based on the column 'CARESEEKING_PCT' from the user-provided file.

In [ ]:
# Export the data

# CSV
save_yearly_incidence(yearly_incidence, DATA_PATH, ".csv", write_csv)

# Parquet
save_yearly_incidence(yearly_incidence, DATA_PATH, ".parquet", arrow::write_parquet)